<?xml version="1.0" encoding="UTF-8" ?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
		http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>io.goobi.viewer</groupId>
		<artifactId>viewer</artifactId>
		<version>${revision}${changelist}</version>
	</parent>
	<groupId>io.goobi.viewer.theme</groupId>
	<artifactId>theme-reference</artifactId>
	<version>${revision}${changelist}</version>
	<packaging>war</packaging>

	<name>Goobi viewer - Theme Reference</name>

	<properties>
		<revision>26.05</revision>
		<changelist>-SNAPSHOT</changelist>
		<themeName>reference</themeName>
		<maven.build.timestamp.format>yyyy-MM-dd_HH-mm</maven.build.timestamp.format>
	</properties>


	<dependencies>
		<dependency>
			<groupId>io.goobi.viewer</groupId>
			<artifactId>viewer-core</artifactId>
			<version>${parent.version}</version>
		</dependency>
		<dependency>
			<groupId>io.goobi.viewer</groupId>
			<artifactId>viewer-config</artifactId>
			<version>${parent.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>io.goobi.viewer</groupId>
			<artifactId>viewer-connector</artifactId>
			<version>${parent.version}</version>
		</dependency>
	</dependencies>


	<profiles>
		<profile>
			<id>crowdsourcing</id>
			<dependencies>
				<dependency>
					<groupId>io.goobi.viewer.module</groupId>
					<artifactId>module-crowdsourcing</artifactId>
					<version>${project.version}</version>
				</dependency>
			</dependencies>
		</profile>
	</profiles>


	<build>
		<finalName>viewer</finalName>
		<resources>
			<resource>
				<directory>WebContent</directory>
				<filtering>true</filtering>
				<excludes>
					<exclude>**/*.java</exclude>
				</excludes>
			</resource>
		</resources>
		<plugins>
			<!-- Maven Resource Plugin - important: nonfilteredfileextensions to prevent file corruption -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<configuration>
					<nonFilteredFileExtensions>
						<nonFilteredFileExtension>ico</nonFilteredFileExtension>
						<nonFilteredFileExtension>eot</nonFilteredFileExtension>
						<nonFilteredFileExtension>svg</nonFilteredFileExtension>
						<nonFilteredFileExtension>ttf</nonFilteredFileExtension>
						<nonFilteredFileExtension>woff</nonFilteredFileExtension>
						<nonFilteredFileExtension>woff2</nonFilteredFileExtension>
						<nonFilteredFileExtension>svg</nonFilteredFileExtension>
					</nonFilteredFileExtensions>
				</configuration>
			</plugin>

			<!-- Maven Compiler Plugin -->
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
			</plugin>
			<!-- Maven Dependency Plugin -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<!-- Config files -->
					<execution>
						<id>unpack-config</id>
						<goals>
							<goal>unpack-dependencies</goal>
						</goals>
						<phase>prepare-package</phase>
						<configuration>
							<outputDirectory>${project.build.directory}/config/WEB-INF/classes/</outputDirectory>
							<excludeGroupIds>io.goobi.viewer.module</excludeGroupIds>
							<excludeArtifactIds>viewer-core,viewer-connector</excludeArtifactIds>
							<includeArtifactIds>viewer-config</includeArtifactIds>
							<excludes>MANIFEST.MF,**/pom.*,install/,docker/,**/*.class,web-fragment.xml</excludes>
							<excludeTransitive>true</excludeTransitive>
						</configuration>
					</execution>
					<!-- CMS core templates -->
					<execution>
						<id>unpack-cms-templates</id>
						<goals>
							<goal>unpack-dependencies</goal>
						</goals>
						<phase>prepare-package</phase>
						<configuration>
							<outputDirectory>${project.build.directory}/templates</outputDirectory>
							<excludeGroupIds>io.goobi.viewer.module</excludeGroupIds>
							<excludeArtifactIds>viewer-config,viewer-connector</excludeArtifactIds>
							<includeArtifactIds>viewer-core</includeArtifactIds>
							<includes>META-INF/resources/resources/cms/templates/**/*</includes>
							<excludeTransitive>true</excludeTransitive>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<!-- Maven WAR Plugin -->
			<plugin>
				<artifactId>maven-war-plugin</artifactId>
				<configuration>
					<warSourceDirectory>WebContent</warSourceDirectory>
					<packagingExcludes>**/rebel.xml</packagingExcludes>
					<webResources>
						<webResource>
							<directory>${project.build.directory}/config</directory>
						</webResource>
						<webResource>
							<directory>${project.build.directory}/templates/META-INF/resources</directory>
						</webResource>
					</webResources>
					<archive>
						<addMavenDescriptor>false</addMavenDescriptor>
						<manifestEntries>
							<ApplicationName>Goobi-viewer-theme-${themeName}</ApplicationName>
							<version>${project.version}</version>
							<Implementation-Version>${buildNumber}</Implementation-Version>
							<Implementation-Build-Date>${buildDate}</Implementation-Build-Date>
						</manifestEntries>
					</archive>
				</configuration>
			</plugin>
			<!-- get git version number -->
			<plugin>
				<groupId>pl.project13.maven</groupId>
				<artifactId>git-commit-id-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>revision</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<commitIdGenerationMode>flat</commitIdGenerationMode>
					<gitDescribe>
						<skip>true</skip>
					</gitDescribe>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>buildnumber-maven-plugin</artifactId>
				<executions>
					<execution>
						<phase>validate</phase>
						<goals>
							<goal>create</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<scmDirectory>${project.basedir}</scmDirectory>
					<shortRevisionLength>7</shortRevisionLength>
					<doCheck>false</doCheck>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
